owner: Cyb3r-Jak3
repo: uptime-stats

sites:
  - name: Portfolio
    url: https://www.jwhite.network
  - name: Portfolio (Self Hosted)
    url: https://portfolio.jwhite.network
  - name: API
    url: https://api.jwhite.network
  - name: Project Site
    url: https://projects.jwhite.network

status-website:
  cname: status.jwhite.network
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JWhite Status
  introTitle: Uptime Monitor of my sites and services. 
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
