owner: Cyb3r-Jak3
repo: uptime-stats

sites:
  - name: Portfolio
    url: https://www.cyberjake.xyz
    icon: https://www.cyberjake.xyz/images/favicon.png
  - name: Portfolio (Self Hosted)
    url: https://portfolio.cyberjake.xyz
    icon: https://portfolio.cyberjake.xyz/images/favicon.png
  - name: API
    url: https://api.cyberjake.xyz
    icon: https://www.cyberjake.xyz/images/favicon.png
    method: GET
  - name: Blog
    url: https://blog.cyberjake.xyz
    icon: https://www.cyberjake.xyz/images/favicon.png
  - name: Project Site
    url: https://projects.jwhite.network
    icon: https://projects.jwhite.network/assets/images/favicon/favicon-16x16.png
  - name: Status Site
    url: https://status.cyberjake.xyz
    icon: https://raw.githubusercontent.com/Cyb3r-Jak3/uptime-stats/master/assets/upptime-icon.svg
  - name: DNS API
    url: https://dns.cyberjake.xyz/api/
    icon: https://lookup.cyberjake.xyz/favicon.ico
  - name: Lookup Client
    url: https://lookup.cyberjake.xyz/
    icon: https://lookup.cyberjake.xyz/favicon.ico

status-website:
  cname: status.cyberjake.xyz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cyb3r-Jak3 Status
  introTitle: Uptime Monitor of my sites and services. 
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: Portfolio
      href: https://www.cyberjake.xyz
    - title: Blog
      href: https://blog.cyberjake.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - Cyb3r-Jak3
runner: ["ubuntu-latest"]

workflowSchedule:
  responseTime: "0 * * * *"
  uptime: "0 0 * * *"