owner: Cyb3r-Jak3
repo: uptime-stats

sites:
  - name: Portfolio
    url: https://www.cyberjake.xyz
    icon: https://www.cyberjake.xyz/images/favicon.png
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: Portfolio (Self Hosted)
    url: https://portfolio.cyberjake.xyz
    icon: https://portfolio.cyberjake.xyz/images/favicon.png
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: API
    url: https://api.cyberjake.xyz/version
    icon: https://www.cyberjake.xyz/images/favicon.png
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: Blog
    url: https://blog.cyberjake.xyz
    icon: https://www.cyberjake.xyz/images/favicon.png
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: Status Site
    url: https://status.cyberjake.xyz
    icon: https://raw.githubusercontent.com/Cyb3r-Jak3/uptime-stats/master/assets/upptime-icon.svg
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: DNS API
    url: https://dns.cyberjake.xyz/api/
    icon: https://rdap.cyberjake.xyz/favicon.ico
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: Lookup Client
    url: https://rdap.cyberjake.xyz/
    icon: https://rdap.cyberjake.xyz/favicon.ico
    headers:
      - "User-Agent: Cyb3r Uptime"
  - name: Send
    url: https://send.cyberjake.xyz/
    headers:
      - "User-Agent: Cyb3r Uptime"

status-website:
  cname: status.cyberjake.xyz
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Cyb3r-Jak3 Status
  introTitle: Uptime Monitor of my sites and services. 
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: Portfolio
      href: https://www.cyberjake.xyz
    - title: Blog
      href: https://blog.cyberjake.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - Cyb3r-Jak3
runner: ["ubuntu-latest"]

workflowSchedule:
  responseTime: "0 * * * *"
  uptime: "*/5 * * * *"
