owner: Cyb3r-Jak3
repo: uptime-stats

sites:
  - name: Portfolio
    url: https://www.jwhite.network
    icon: https://www.jwhite.network/images/favicon.png
  - name: Portfolio (Self Hosted)
    url: https://portfolio.jwhite.network
    icon: https://www.jwhite.network/images/favicon.png
  - name: API
    url: https://api.jwhite.network
    icon: https://www.jwhite.network/images/favicon.png
    expectedStatusCodes:
      - 308
  - name: Project Site
    url: https://projects.jwhite.network
    icon: https://projects.jwhite.network/assets/images/favicon/favicon-16x16.png

status-website:
  cname: status.jwhite.network
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: JWhite Status
  introTitle: Uptime Monitor of my sites and services. 
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - Cyb3r-Jak3

status-website:
  theme: ocean